"""Chibi samurai walk sheet: 32x32 cells, 3 cols (step, stand, step) x 4 rows (down, left, right, up)."""
from PIL import Image

PAL = {
    "O": (0x1B, 0x14, 0x28),  # outline / eyes
    "H": (0x2E, 0x2A, 0x40),  # hair
    "h": (0x55, 0x50, 0x78),  # hair highlight
    "S": (0xF6, 0xCC, 0xA6),  # skin
    "s": (0xD9, 0x9A, 0x7A),  # skin shadow / mouth
    "p": (0xF0, 0x8A, 0x8A),  # blush
    "W": (0xFF, 0xFF, 0xFF),  # eye highlight
    "R": (0xC8, 0x32, 0x3C),  # headband / obi
    "B": (0x2F, 0x4F, 0x8F),  # kimono
    "L": (0x5B, 0x80, 0xC8),  # kimono light
    "T": (0xEE, 0xE6, 0xD6),  # collar / tabi
    "G": (0x5C, 0x54, 0x70),  # hakama
    "g": (0x40, 0x3A, 0x55),  # hakama pleat
    "Y": (0xE0, 0xB0, 0x40),  # tsuba
    "M": (0xE8, 0xE8, 0xF0),  # hilt wrap
    "k": (0x2A, 0x1F, 0x1A),  # scabbard
    "N": (0x8A, 0x5A, 0x3A),  # sandal
    "t": (0xB4, 0xAC, 0xA4),  # far tabi
    "D": (0x5A, 0x3A, 0x26),  # far sandal
}

FRONT = """
................................
..............OOOO..............
.............OhHHHO.............
.............OHHHHO.............
...........OOOOOOOOOO...........
.........OOHhhHHHHHHHOO.........
........OHhhHHHHHHHHHHHO........
........OHhHHHHHHHHHHHHO........
........ORRRRRRRRRRRRRRO........
........OHHSSSSSSSSSSHHO........
........OHSOOOSSSSOOOSHO........
........OHSSOWSSSSOWSSHO........
........OHSSOOSSSSOOSSHO........
........OSSpSSSSSSSSpSSO........
........OSSSSSSssSSSSSSO........
.........OSSSSSSSSSSSSO.........
..........OOSSSSSSSSOO..........
........OOBBBTSSSSTBBBOO........
.......OBBBBBTTSSTTBBBBBO.......
.......OBBLBBBTTTTBBBLBOO.......
......OBBLBBBBBTTBBBBBLMBO......
......OBBLBBBBBBBBBBBMLBBO......
......OBBBORRRRRRRRYROBBBO......
......OSSOORRRRRRRRRROOSSO......
......OSSOOGGGGGGGGGGOOSSOk.....
.......OO.OGGGGgGGGGGO.OO.kk....
..........OGGGGgGGGGGO.....k....
..........OGGGGgGGGGGO..........
..........OOOOOOOOOOOO..........
................................
................................
................................
"""

SIDE = """
................................
................OOOO............
...............OhHHHO...........
...............OHHHHHO..........
...........OOOOOOOOOO...........
.........OOHHhhHHHHHHOO.........
........OHHhhHHHHHHHHHHO........
........OHHHHHHHHHHHHHHO........
........ORRRRRRRRRRRRRRORR......
........OSSSSSSSSHHHHHHO.RR.....
........OSOOSSSSSHHHHHHO...R....
........OSOWSSSSssHHHHHO........
.......OSSOOSSSSssHHHHHO........
........OSSpSSSSSSHHHHHO........
........OSssSSSSSSSHHHO.........
.........OSSSSSSSSSSSO..........
..........OOSSSSSSSOO...........
..........OOTTSSBBBOO...........
.........OBTTTBBBBBBBO..........
.........OBBTTBBLLBBBBO.........
........OBBBBTBLBBBBBBBO........
......MMOBBBBBOLBBBBBBBO........
.......MYRRRRROBBBBBBBBO........
........ORRRRROSSBBBBBBO........
........OGGGGGOSSOOOOOOkk.......
........OGGGGGGOOGGGGOkkk.......
........OGGGgGGGGGGGGO..kk......
........OGGGgGGGGGgGGO...kk.....
........OOOOOOOOOOOOOO..........
................................
................................
................................
"""

BACK = """
................................
..............OOOO..............
.............OhHHHO.............
.............OHHHHO.............
...........OOOOOOOOOO...........
.........OOHhhHHHHHHHOO.........
........OHhhHHHHHHHHHHHO........
........OHhHHHHHHHHHHHHO........
........ORRRRRRRRRRRRRRO........
........OHHHHHHRRHHHHHHO........
........OHHHHHRRRRHHHHHO........
........OHHHHHRHHRHHHHHO........
........OHHHHHRHHRHHHHHO........
........OHHHHHHHHHHHHHHO........
........OHHHHHHHHHHHHHHO........
.........OHHHHHHHHHHHHO.........
..........OOHHHSSHHHOO..........
..........OOBBBTTBBBOO..........
.......OBBBBBBBBBBBBBBBBO.......
.......OBBLBBBBBBBBBBLBBO.......
......OBBLBBBBBBBBBBBBLBBO......
......OBBLBBBBBBBBBBBBLBBO......
......OBBBORRRRRRRRRROBBBO......
......OSSOORRRRRRRRRROOSSO......
.....kOSSOOGGGGGGGGGGOOSSO......
...kk..OO.OGGGGgGGGGGO.OO.......
..k.......OGGGGgGGGGGO..........
..........OGGGGgGGGGGO..........
..........OOOOOOOOOOOO..........
................................
................................
................................
"""


def parse(s):
    rows = [r for r in s.strip("\n").split("\n")]
    assert len(rows) == 32, len(rows)
    for i, r in enumerate(rows):
        assert len(r) == 32, (i, len(r), r)
    return [list(r) for r in rows]


def stamp(g, pattern, x0, y0):
    for dy, row in enumerate(pattern):
        for dx, c in enumerate(row):
            if c != ".":
                g[y0 + dy][x0 + dx] = c


FOOT = ["OTTO", "ONNO", "OOOO"]
FOOT_LONG = ["OTTO", "OTTO", "ONNO", "OOOO"]
SFOOT = [".OTTO", "ONNNO", "OOOOO"]
SFOOT_LONG = [".OTTO", ".OTTO", "ONNNO", "OOOOO"]


def far(pat):
    return [r.replace("T", "t").replace("N", "D") for r in pat]


def stamp_behind(g, pattern, x0, y0):
    for dy, row in enumerate(pattern):
        for dx, c in enumerate(row):
            if c != "." and g[y0 + dy][x0 + dx] == ".":
                g[y0 + dy][x0 + dx] = c


def bob_up(g, b):
    return g[b:] + [["."] * 32 for _ in range(b)]


def foot(g, pat, long_pat, x, state, b):
    """state: 'stand' | 'planted' | 'lifted'. b = body bob (px up)."""
    if b == 0:
        stamp(g, pat, x, 29)
    elif state == "lifted":
        stamp_behind(g, pat, x, 27)  # tucked 2px up under the hem
    else:
        stamp(g, long_pat, x, 28)  # leg stretches to keep contact


def front_like(base, step):
    b = 0 if step == 1 else 1
    g = bob_up(parse(base), b)
    foot(g, FOOT, FOOT_LONG, 11, "lifted" if step == 0 else "planted", b)
    foot(g, FOOT, FOOT_LONG, 17, "lifted" if step == 2 else "planted", b)
    return g


def side(step):
    """Facing left; far foot is darker and drawn first."""
    b = 0 if step == 1 else 1
    g = bob_up(parse(SIDE), b)
    if step == 1:
        foot(g, far(SFOOT), far(SFOOT_LONG), 14, "stand", 0)
        stamp(g, SFOOT, 9, 29)
        return g
    near_fwd = step == 0
    fwd, back_ = 6, 17
    nx, fx = (fwd, back_) if near_fwd else (back_, fwd)
    n_state, f_state = ("planted", "lifted") if near_fwd else ("lifted", "planted")
    foot(g, far(SFOOT), far(SFOOT_LONG), fx, f_state, b)
    foot(g, SFOOT, SFOOT_LONG, nx, n_state, b)
    return g


def mirror(g):
    return [r[::-1] for r in g]


def sheet():
    rows = [
        [front_like(FRONT, s) for s in range(3)],
        [side(s) for s in range(3)],
        [mirror(side(s)) for s in range(3)],
        [front_like(BACK, s) for s in range(3)],
    ]
    img = Image.new("RGBA", (96, 128), (0, 0, 0, 0))
    for r, cells in enumerate(rows):
        for c, g in enumerate(cells):
            for y in range(32):
                for x in range(32):
                    if g[y][x] != ".":
                        img.putpixel((c * 32 + x, r * 32 + y), PAL[g[y][x]] + (255,))
    return img


if __name__ == "__main__":
    import sys

    sheet().save(sys.argv[1])
