import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {FBXLoader} from 'three/addons/loaders/FBXLoader.js';
import {VRMLoaderPlugin} from '@pixiv/three-vrm';
const $=id=>document.getElementById(id),canvas=document.querySelector('canvas');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
const scene=new THREE.Scene();scene.background=new THREE.Color('#b7b7b7');scene.add(new THREE.HemisphereLight(0xffffff,0x726778,2.5));for(const [x,y,z,p] of [[-1.2,2.5,1.5,3],[1.5,1.6,.4,1.5]]){const l=new THREE.DirectionalLight(0xffffff,p);l.position.set(x,y,z);scene.add(l);}scene.add(new THREE.GridHelper(3,12,0x888888,0x999999));
const camera=new THREE.OrthographicCamera(-.8,.8,.8,-.8,.01,100);let vrm,mixer,action,time=0,playing=false,recording=false,recorder,recordURL,helper,selectionRevision=0;const clips=new Map(),rest=new Map();
function render(){const a=+$('angle').value*Math.PI/180;camera.position.set(3*Math.sin(a),.55,3*Math.cos(a));camera.lookAt(0,.55,0);renderer.render(scene,camera);}
function resize(){const w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);const aspect=w/h,half=.70*Math.max(1,1/aspect);camera.top=half;camera.bottom=-half;camera.left=-half*aspect;camera.right=half*aspect;camera.updateProjectionMatrix();render();}new ResizeObserver(resize).observe(canvas);
const loader=new GLTFLoader();loader.register(p=>new VRMLoaderPlugin(p));
function rotation(name,x=0,y=0,z=0){const bone=vrm.humanoid.getNormalizedBoneNode(name);if(!bone)return;bone.quaternion.copy(rest.get(name).q).multiply(new THREE.Quaternion().setFromEuler(new THREE.Euler(x,y,z)));}
function resetPose(){for(const [name,r] of rest){const n=vrm.humanoid.getNormalizedBoneNode(name);n.position.copy(r.p);n.quaternion.copy(r.q);n.scale.copy(r.s);}}
function authored(kind,t){const q=(1-Math.cos(t/3*Math.PI*2))/2,rad=Math.PI/180;for(const side of ['left','right']){const sign=side==='left'?1:-1;rotation(side+'UpperArm',0,0,-sign*70*rad);if(kind==='arms'){rotation(side+'UpperArm',0,0,sign*(-70+145*q)*rad);rotation(side+'LowerArm',0,-sign*110*q*rad,0);}if(kind==='squat'||kind==='jump'){rotation(side+'UpperLeg',-85*q*rad,0,sign*12*q*rad);rotation(side+'LowerLeg',125*q*rad);rotation(side+'Foot',-40*q*rad);rotation(side+'UpperArm',-50*q*rad,0,-sign*45*rad);}if(kind==='kick'){const k=side==='left'?q:0;rotation(side+'UpperLeg',-110*k*rad,0,sign*15*k*rad);rotation(side+'LowerLeg',30*k*rad);rotation(side+'UpperArm',0,0,-sign*30*rad);}}
 if(kind==='squat'){rotation('spine',22*q*rad);vrm.humanoid.getNormalizedBoneNode('hips').position.y-=.08*q;}
 if(kind==='jump')vrm.humanoid.getNormalizedBoneNode('hips').position.y+=.18*Math.sin(Math.PI*q);
 if(kind==='twist'){rotation('spine',15*q*rad,35*q*rad,12*q*rad);rotation('chest',0,25*q*rad);rotation('neck',0,-25*q*rad);rotation('head',-18*q*rad,-25*q*rad);}
}
function face(){for(const n of ['happy','angry','sad','relaxed','blink','surprised','aa','ih','ou','ee','oh'])vrm.expressionManager.setValue(n,0);const f=$('face').value;if(f!=='neutral')vrm.expressionManager.setValue(f,1);if(f==='happy')vrm.expressionManager.setValue('aa',.65);if(f==='surprised')vrm.expressionManager.setValue('oh',.65);}
function seek(t){if(!vrm)return;time=Math.max(0,Math.min(duration(),t));resetPose();if(action){action.paused=false;mixer.setTime(time);}else if($('motion').value!=='neutral')authored($('motion').value,time);face();vrm.update(0);vrm.scene.updateMatrixWorld(true);vrm.scene.traverse(o=>{if(o.isSkinnedMesh)o.skeleton.update();});helper?.updateMatrixWorld(true);$('time').value=time;$('timeOut').textContent=time.toFixed(2)+'秒';render();}
function duration(){return clips.get($('motion').value)?.duration||3;}
function stop(){playing=false;$('play').textContent='再生';}
async function select(kind){const version=++selectionRevision;stop();if(action){action.stop();action=null;}mixer.stopAllAction();resetPose();$('motion').value=kind;if(kind==='samba'){
 if(!clips.has(kind)){const result=await loadDance();clips.set(kind,result.clip);window.bodyStudy.retarget=result.report;}if(version!==selectionRevision)return;
 action=mixer.clipAction(clips.get(kind));action.setLoop(THREE.LoopOnce,1);action.clampWhenFinished=true;action.reset().play();
 }$('time').max=duration();seek(0);$('status').textContent='検査用の再生';saveQuery();}
// Rest-frame rotation conversion follows the method documented by pixiv/three-vrm's
// MIT-licensed humanoidAnimation example. Translation is restricted to hips;
// source segment translations must never resize this mascot's limbs.
async function loadDance(){const manager=new THREE.LoadingManager();manager.setURLModifier(url=>/\.(png|jpe?g|tga)$/i.test(url)?'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==':url);const asset=await new FBXLoader(manager).loadAsync('/artifacts/body-motion/samba.fbx');asset.updateMatrixWorld(true);const clip=asset.animations[0];if(!clip)throw Error('FBXにモーションがありません');
 const map={Hips:'hips',Spine:'spine',Spine1:'chest',Spine2:'upperChest',Neck:'neck',Head:'head',LeftShoulder:'leftShoulder',RightShoulder:'rightShoulder'};for(const [a,b] of [['Left','left'],['Right','right']])for(const [src,dst] of [['Arm','UpperArm'],['ForeArm','LowerArm'],['Hand','Hand'],['UpLeg','UpperLeg'],['Leg','LowerLeg'],['Foot','Foot'],['ToeBase','Toes']])map[a+src]=b+dst;
 const sourceBones={};asset.traverse(o=>{if(o.isBone){const key=o.name.replace(/^mixamorig:?/,'');if(!sourceBones[key])sourceBones[key]=o;}});const hips=sourceBones.Hips;if(!hips)throw Error('Mixamo hipsが見つかりません');const scale=rest.get('hips').p.y/hips.position.y,tracks=[],mapped=new Set(),skipped=[];if(!Number.isFinite(scale)||scale<=0)throw Error('腰の高さの換算が不正です');
 for(const track of clip.tracks){const at=track.name.lastIndexOf('.'),name=track.name.slice(0,at),property=track.name.slice(at+1),key=name.replace(/^mixamorig:?/,''),target=map[key],bone=target&&vrm.humanoid.getNormalizedBoneNode(target),src=sourceBones[key];if(!bone||!src){skipped.push(track.name);continue;}
 if(property==='quaternion'){const inv=src.getWorldQuaternion(new THREE.Quaternion()).invert(),parent=src.parent.getWorldQuaternion(new THREE.Quaternion()),values=new Float32Array(track.values.length);for(let i=0;i<values.length;i+=4)new THREE.Quaternion().fromArray(track.values,i).premultiply(parent).multiply(inv).normalize().toArray(values,i);tracks.push(new THREE.QuaternionKeyframeTrack(bone.name+'.quaternion',track.times,values));mapped.add(target);}
 else if(property==='position'&&target==='hips'){const values=new Float32Array(track.values.length);for(let i=0;i<values.length;i+=3){values[i]=(track.values[i]-hips.position.x)*scale+rest.get('hips').p.x;values[i+1]=(track.values[i+1]-hips.position.y)*scale+rest.get('hips').p.y;values[i+2]=(track.values[i+2]-hips.position.z)*scale+rest.get('hips').p.z;}tracks.push(new THREE.VectorKeyframeTrack(bone.name+'.position',track.times,values));}}
 if(mapped.size<15)throw Error('対応する骨が不足しています');return {clip:new THREE.AnimationClip('Samba Dancing',clip.duration,tracks),report:{sourceClip:clip.name,duration:clip.duration,hipsScale:scale,mapped:[...mapped],skipped}};
}
function audit(){vrm.scene.updateMatrixWorld(true);const summary={meshes:[],bones:[]};for(const [name] of rest){const n=vrm.humanoid.getRawBoneNode(name);summary.bones.push({name,position:n.getWorldPosition(new THREE.Vector3()).toArray()});}vrm.scene.traverse(o=>{if(!o.isSkinnedMesh)return;const pos=o.geometry.getAttribute('position'),point=new THREE.Vector3(),min=new THREE.Vector3(Infinity,Infinity,Infinity),max=new THREE.Vector3(-Infinity,-Infinity,-Infinity);let finite=true;for(let i=0;i<pos.count;i++){o.getVertexPosition(i,point).applyMatrix4(o.matrixWorld);finite&&=point.toArray().every(Number.isFinite);min.min(point);max.max(point);}summary.meshes.push({name:o.name,vertices:pos.count,finite,min:min.toArray(),max:max.toArray()});});return summary;}
function saveQuery(){history.replaceState(null,'','?'+new URLSearchParams({motion:$('motion').value,angle:$('angle').value,t:time.toFixed(3)}));}
$('motion').onchange=()=>select($('motion').value).catch(e=>{$('status').textContent=String(e);window.bodyStudy.error=String(e);});$('time').oninput=()=>{stop();seek(+$('time').value);saveQuery();};$('play').onclick=()=>{if(playing)stop();else {if(time>=duration())seek(0);playing=true;$('play').textContent='一時停止';}};$('reset').onclick=()=>{stop();seek(0);};$('prev').onclick=()=>{stop();seek(time-1/30);saveQuery();};$('next').onclick=()=>{stop();seek(time+1/30);saveQuery();};$('angle').onchange=()=>{render();saveQuery();};$('face').onchange=()=>seek(time);$('bones').onchange=()=>{helper.visible=$('bones').checked;render();};
function recordingControls(value){for(const id of ['motion','time','play','reset','prev','next','speed','record'])$(id).disabled=value;}
$('record').onclick=()=>{if(recording)return;const type=['video/webm;codecs=vp9','video/webm'].find(t=>MediaRecorder.isTypeSupported(t));if(!type){$('status').textContent='この環境では録画できません';return;}const stream=canvas.captureStream(30),chunks=[];recorder=new MediaRecorder(stream,{mimeType:type});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());if(recordURL)URL.revokeObjectURL(recordURL);recordURL=URL.createObjectURL(new Blob(chunks,{type}));$('download').href=recordURL;$('download').download='miineko-'+$('motion').value+'.webm';$('download').hidden=false;recording=false;recordingControls(false);};recording=true;recordingControls(true);seek(0);$('speed').value='1';recorder.start();playing=true;};
let last=performance.now();function frame(now){const dt=Math.min(.1,(now-last)/1000);last=now;if(playing&&vrm){const next=time+dt*(+$('speed').value);seek(Math.min(next,duration()));if(next>=duration()){if(recording){stop();recorder.stop();}else seek(0);}}requestAnimationFrame(frame);}requestAnimationFrame(frame);document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();if(recording)recorder.stop();}});
window.bodyStudy={renderer,scene,camera,seek,select,stop,audit,get vrm(){return vrm;},get duration(){return duration();},get time(){return time;}};
try{vrm=(await loader.loadAsync('/artifacts/blink-aligned/continuous-blink.vrm')).userData.vrm;scene.add(vrm.scene);vrm.scene.traverse(o=>{o.frustumCulled=false;});for(const name of Object.keys(vrm.humanoid.humanBones)){const n=vrm.humanoid.getNormalizedBoneNode(name);if(n)rest.set(name,{p:n.position.clone(),q:n.quaternion.clone(),s:n.scale.clone()});}mixer=new THREE.AnimationMixer(vrm.scene);helper=new THREE.SkeletonHelper(vrm.scene);helper.visible=false;scene.add(helper);resize();const params=new URLSearchParams(location.search);if([...$('angle').options].some(o=>o.value===params.get('angle')))$('angle').value=params.get('angle');await select(params.get('motion')||'neutral');const t=Number(params.get('t')||0);seek(Number.isFinite(t)?t:0);saveQuery();window.ready=true;}catch(e){$('status').textContent=String(e);window.bodyStudy.error=String(e);}
