import puppeteer from 'puppeteer-core';
const browser=await puppeteer.launch({executablePath:process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
try{const page=await browser.newPage();await page.setViewport({width:1200,height:1400});await page.goto('http://127.0.0.1:52714/expression-study.html?variant=lid-rim-clean&opening=0&blink=1&angle=45');await page.waitForFunction(()=>window.ready);const canvas=await page.$('canvas');await (await page.$('canvas')).screenshot({path:'artifacts/lid-gap-review/original.png'});
await page.evaluate(()=>{study.current.scene.traverse(o=>{if(!o.isMesh||!o.name.startsWith('Surface_Lid'))return;});const meshes=[];study.current.scene.traverse(o=>{if(o.isMesh){const mats=[o.material].flat();for(const m of mats){if(m.name.startsWith('Surface Lid')&&!m.name.endsWith('ink')){const c=o.geometry.getAttribute('color');meshes.push({name:o.name,material:m.name,count:c?.count,itemSize:c?.itemSize});}}}});window.diagnosticMeshes=meshes;});console.log(await page.evaluate(()=>diagnosticMeshes));
for(const mode of ['expand-2','expand-4']){await page.reload();await page.waitForFunction(()=>window.ready);await page.evaluate(async mode=>{const T=await import('/node_modules/three/build/three.module.js');study.current.scene.traverse(o=>{if(!o.isMesh)return;for(const m of [o.material].flat()){
 if(m.name.startsWith('Surface Lid')&&!m.name.endsWith('ink')){if(mode.startsWith('expand-')){const p=o.geometry.getAttribute('position'),cx=m.name.includes(' L ')? .1764:-.1848,k=mode==='expand-2'?1.02:1.04;for(let i=0;i<p.count;i++){p.setX(i,cx+(p.getX(i)-cx)*k);p.setY(i,.619+(p.getY(i)-.619)*k);p.setZ(i,p.getZ(i)+.0005);}p.needsUpdate=true;}if(mode==='double-side'){m.side=T.DoubleSide;m.needsUpdate=true;}if(mode==='uniform-color'){const c=o.geometry.getAttribute('color');const mean=[0,0,0];let n=0;for(let i=0;i<c.count;i++){if(c.getW(i)>.98){mean[0]+=c.getX(i);mean[1]+=c.getY(i);mean[2]+=c.getZ(i);n++;}}for(let i=0;i<c.count;i++){c.setXYZ(i,...mean.map(v=>v/n));}c.needsUpdate=true;}if(mode.startsWith('offset-')){const p=o.geometry.getAttribute('position');for(let i=0;i<p.count;i++)p.setZ(i,p.getZ(i)+(mode==='offset-1'?.001:.003));p.needsUpdate=true;}if(mode==='solid-white'){o.material=new T.MeshBasicMaterial({map:m.map,transparent:true,side:m.side,depthWrite:m.depthWrite});}if(mode==='alpha'){const c=o.geometry.getAttribute('color');for(let i=0;i<c.count;i++)c.setW(i,1);c.needsUpdate=true;}
 if(mode==='flat-lids'){o.material=new T.MeshBasicMaterial({map:m.map,vertexColors:true,transparent:true,side:m.side,depthWrite:m.depthWrite});}}
 if(mode==='no-source-normal'&&!m.name.startsWith('Surface Lid'))m.normalScale?.set(0,0);
 }});study.renderer.render(study.scene,study.camera);},mode);await (await page.$('canvas')).screenshot({path:`artifacts/lid-gap-review/${mode}.png`});}
}finally{await browser.close();}
